spring.application.name=robot-SEO-monitor

# SERVER
server.forward-headers-strategy=framework
server.servlet.context-path=/api

# JPA / HIBERNATE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# SCHEDULER
app.scheduler.enabled=true
app.scheduler.fixed-rate-ms=240000

# NOTIFICATION
app.notification.webhook-url=https://n8n.javik.online/webhook/447ed3a2-9e28-478d-b29c-2597d6d19015
app.notification.dashboard-url=http://5.199.138.20:8081/api