version: "3.3"

networks:
  seo-monitor-net:

services:
  seo-monitor-backend:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${API_PORT}:${API_PORT}"

    networks:
      - seo-monitor-net

    depends_on:
      - seo-monitor-postgres

    env_file:
      - .env

  seo-monitor-postgres:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    networks:
      - seo-monitor-net

    volumes:
      - seo_monitor_postgres_data:/var/lib/postgresql/data

volumes:
  seo_monitor_postgres_data: